Saml auth
i2b2/i2b2-core-server pull request #21
Opened 2022-01-28 20:23 UTC by kvb2univpitt

2022-02-21 22:02 UTC, jklann requested changes
Very hard to tell what if anything changed in the second commit with all the formatting changes. Maybe you could give line numbers? Or is it easier to cross-reference with your repository?

2022-02-28 19:59 UTC, kvb2univpitt commented
@jklann @mikemendis I reverted all the changes in the repo.  I then apply all of my changes without reformatting the code and pushed to the repo.  Now, you can clearly see where all the changes are made.

2022-02-28 20:02 UTC, kvb2univpitt commented on edu.harvard.i2b2.pm/src/edu/harvard/i2b2/pm/delegate/ServicesHandler.java
> +                                                System.out.println(f3.getName());
I reverted all the changes.

2022-03-28 18:30 UTC, jklann reviewed
Code changes look good (except the one println change). Do we need the final commit (ecf99eb324e72dacb881c37d61ccf7bcffbffd2b) that does reformatting?

2022-03-28 18:30 UTC, jklann commented on edu.harvard.i2b2.pm/src/edu/harvard/i2b2/pm/delegate/ServicesHandler.java
> +                                                System.out.println(f3.getName());
I still think you mean log.debug instead of println?

2022-03-28 19:32 UTC, kvb2univpitt commented
> Code changes look good (except the one println change). Do we need the final commit ([ecf99eb](https://github.com/i2b2/i2b2-core-server/commit/ecf99eb324e72dacb881c37d61ccf7bcffbffd2b)) that does reformatting?

That println is no long there.

2022-03-28 20:14 UTC, merged