[Task]: snowflake driver support for i2b2 cells
i2b2/i2b2-core-server pull request #22
Opened 2023-07-27 17:51 UTC by shossain-mizzou

- Provided Snowflake JDBC driver support for all core cells
- Sample examples are given to configure Wildfly datasource for Snowflake in the /etc/jboss/ directory

2023-08-18 18:18 UTC, shossain-mizzou commented
Hi @jklann @mikemendis , is it possible to refactor the last commit: 'Added Quartz and created web service calls'. 
It changed the character encoding in all files across the project, however there were no changes in the files. Rebasing/merging on top of that commit causing the issue.

2023-08-25 18:32 UTC, jklann requested changes
The part of the commit I reviewed looks great - at least it doesn't break anything. But I stopped 20 files short because 90% of the changes are tabs being inserted or deleted or the same line is removed and then put back - perhaps a line ending issue still? Is there any way you can get rid of this problem? It would be much easier to finish reviewing and it would be cleaner as a commit. Thanks!

2023-08-25 18:32 UTC, jklann commented on edu.harvard.i2b2.crc/src/server/edu/harvard/i2b2/crc/dao/setfinder/QueryExecutorHelperDao.java
This entire file still looks like it changed - another line ending issue?

2023-08-28 19:22 UTC, shossain-mizzou commented
Hi @jklann , I have reverted back all the changes related to white spaces. Would you please review again? Thanks!

2025-08-06 15:26 UTC, closed without merging